"""initial_generation

Revision ID: 974b951041b0
Revises:
Create Date: 2022-11-04 13:14:28.085131

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '974b951041b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.get_context().autocommit_block():
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table(
            'environment',
            sa.Column('id', sa.String(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_table(
            'a',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('environment_id', sa.String(), nullable=False),
            sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_table(
            'b',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('environment_id', sa.String(), nullable=False),
            sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_table(
            'link',
            sa.Column('a_id', sa.String(), nullable=False),
            sa.Column('b_id', sa.String(), nullable=False),
            sa.Column('environment_id', sa.String(), nullable=False),
            sa.ForeignKeyConstraint(['environment_id', 'a_id'], ['a.environment_id', 'a.id'], name='fk_1'),
            sa.ForeignKeyConstraint(['environment_id', 'b_id'], ['b.environment_id', 'b.id'], name='fk_2'),
            sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
            sa.PrimaryKeyConstraint('environment_id', 'a_id', 'b_id', name='pk_test')
        )
        # ### end Alembic commands ###


def downgrade():
    with op.get_context().autocommit_block():
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_table('link')
        op.drop_table('b')
        op.drop_table('a')
        op.drop_table('environment')
        # ### end Alembic commands ###
